# Generated by Django 4.1 on 2023-01-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("host", models.CharField(max_length=64)),
                ("date", models.CharField(max_length=64)),
                ("type", models.CharField(max_length=64)),
                ("soldOut", models.BooleanField()),
            ],
        ),
    ]
