# Generated by Django 4.1 on 2023-01-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venueapp", "0003_seat"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="seating",),
        migrations.AddField(
            model_name="seat",
            name="col",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seat",
            name="row",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(model_name="seat", name="event",),
        migrations.AddField(
            model_name="seat",
            name="event",
            field=models.ManyToManyField(
                blank=True, related_name="seats", to="venueapp.event"
            ),
        ),
    ]
