# Generated by Django 4.1 on 2023-01-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venueapp", "0004_remove_event_seating_seat_col_seat_row_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="seat", name="event",),
        migrations.AddField(
            model_name="seat",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="venueapp.event",
            ),
        ),
    ]
