# Generated by Django 4.1 on 2023-01-14 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venueapp", "0005_remove_seat_event_seat_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="venueapp.event",
            ),
            preserve_default=False,
        ),
    ]
