# Generated by Django 4.1 on 2023-01-14 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venueapp", "0007_remove_seat_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="venueapp.event",
            ),
        ),
    ]
